name:                localcooking-command
version:             0.0.0
git:                 "git@git.localcooking.com:localcooking/localcooking-command"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "Copyright (c) 2018 Local Cooking Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/localcooking-command#readme>

dependencies:
- base >= 4.7 && < 5
- localcooking-db
- localcooking-shared
- localcooking-function
- attoparsec
- emailaddress >= 0.2.0.1
- logging
- persistent
- text
- utf8-string

library:
  source-dirs: src

executables:
  localcooking-command:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localcooking-command
    - logging
    - monad-logger
    - optparse-applicative
    - path-extra >= 0.2.0
    - persistent
    - persistent-postgresql
    - resource-pool
    - safe-exceptions
    - utf8-string

tests:
  localcooking-command-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - localcooking-command
